name: Build and Release WXT Extension

on:
  push:
    branches: ["test-ci"]

jobs:
  build:
    env:
      VITE_BACKEND_SERVER: ${{ secrets.VITE_BACKEND_SERVER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Create .env file
        run: |
          echo "VITE_BACKEND_SERVER=$VITE_BACKEND_SERVER" >> .env

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Zip Chrome release asset
        run: |
          cd .output/chrome-mv3  
          zip -r ../extension-${{ github.ref_name }}-chrome.zip .

      - name: Zip Firefox release asset
        run: |
          wxt zip -b firefox
          cd .output/firefox-mv3
          zip -r ../extension-${{ github.ref_name }}-firefox.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .output/extension-${{ github.ref_name }}-chrome.zip
            .output/extension-${{ github.ref_name }}-firefox.zip
          generate_release_notes: true
